/**
 * Export Utilities
 * Functions for exporting screening results in various formats
 */

/**
 * Export results as JSON file
 */
export const exportAsJSON = (results, timestamp) => {
  const exportData = {
    exportDate: new Date().toISOString(),
    screeningDate: timestamp,
    diagnosis: results.diagnosis,
    risks: {
      insomnia: results.insomniaRisk,
      apnea: results.apneaRisk
    },
    lifestyleIssues: results.lifestyleIssues,
    recommendations: results.recommendations,
    firedRules: results.firedRules,
    inputData: results.inputData
  };

  const dataStr = JSON.stringify(exportData, null, 2);
  const dataBlob = new Blob([dataStr], { type: 'application/json' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `kumeowturu-results-${new Date().getTime()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Helper function to get rule descriptions
 */
const getRuleDescription = (ruleId) => {
  const ruleDescriptions = {
    'R1': 'Sleep duration < 6 hours',
    'R2': 'Sleep duration 6-7 hours',
    'R3': 'Poor sleep quality (score < 5)',
    'R4': 'Moderate sleep quality (score 5-7)',
    'R5': 'Frequent snoring reported',
    'R6': 'BMI > 30 (Obese)',
    'R7': 'BMI 25-30 (Overweight)',
    'R8': 'Age > 50 years',
    'R9': 'High stress level (> 7)',
    'R10': 'Moderate stress level (5-7)',
    'R11': 'Difficulty falling asleep',
    'R12': 'Frequent night awakenings',
    'R13': 'Early morning awakening',
    'R14': 'Daytime sleepiness reported',
    'R15': 'Breathing pauses during sleep',
    'R16': 'Morning headaches',
    'R17': 'Irregular sleep schedule',
    'R18': 'Caffeine consumption before bed',
    'R19': 'Screen time before bed',
    'R20': 'Lack of physical activity',
  };
  return ruleDescriptions[ruleId] || ruleId;
};

/**
 * Export results as TXT file with detailed information
 */
export const exportAsTXT = (results, timestamp) => {
  const reportContent = `Sleep Health Screening Report
========================================

Date: ${timestamp || new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })}
Screening ID: ${results.screeningId || 'N/A'}

DIAGNOSIS
========================================
${results.diagnosis || 'No Sleep Disorder Detected'}

${results.inputData && Object.keys(results.inputData).length > 0 ? `TEST RESULT
========================================
${results.inputData.sleepQualityScore !== undefined ? `Sleep Quality: ${results.inputData.sleepQualityScore}/10\n` : ''}${results.inputData.bmiCategory ? `BMI Category: ${results.inputData.bmiCategory}\n` : ''}${results.inputData.sleepDuration !== undefined ? `Sleep Duration: ${results.inputData.sleepDuration} hours\n` : ''}${results.inputData.stressLevel !== undefined ? `Stress Level: ${results.inputData.stressLevel}/10\n` : ''}
` : ''}RISK ASSESSMENT
========================================
Insomnia Risk: ${(results.insomniaRisk || 'UNKNOWN').toUpperCase()}
Sleep Apnea Risk: ${(results.apneaRisk || 'UNKNOWN').toUpperCase()}

${results.recommendations && results.recommendations.length > 0 ? `RECOMMENDATIONS
========================================
${results.recommendations.map((rec, i) => `${i + 1}. ${rec.replace('REC_', '').replace(/_/g, ' ')}`).join('\n')}

` : ''}${results.firedRules && results.firedRules.length > 0 ? `RULE ENGINE ANALYSIS
========================================
Total Rules Fired: ${results.firedRules.length}

Fired Rules: ${results.firedRules.join(', ')}

Detailed Rule Descriptions:
${results.firedRules.map(rule => `- ${rule}: ${getRuleDescription(rule)}`).join('\n')}

` : ''}========================================
Generated by Kumeowturu
`;

  const blob = new Blob([reportContent], { type: 'text/plain;charset=utf-8;' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `Screening Result - ${results.screeningId || 'UNKNOWN'}.txt`);
  document.body.appendChild(link);
  link.click();
  link.parentNode.removeChild(link);
  window.URL.revokeObjectURL(url);
};

/**
 * Export results as PDF
 * Uses browser print functionality with custom styling
 */
export const exportAsPDF = (results, timestamp) => {
  // Create a new window with print-friendly content
  const printWindow = window.open('', '_blank');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="description" content="Sleep Health Screening Report">
      <title>Screening Result - ${results.screeningId || 'UNKNOWN'}</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          padding: 40px;
          color: #333;
          line-height: 1.6;
          max-width: 800px;
          margin: 0 auto;
        }
        
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 3px solid #7C3AED;
        }
        
        .title {
          font-size: 28px;
          font-weight: bold;
          color: #7C3AED;
          margin-bottom: 5px;
        }
        
        .separator {
          border: none;
          border-top: 2px solid #E5E7EB;
          margin: 20px 0;
        }
        
        .meta-info {
          display: flex;
          justify-content: space-between;
          margin-bottom: 10px;
          font-size: 14px;
          color: #6B7280;
        }
        
        .section {
          margin-bottom: 25px;
          page-break-inside: avoid;
        }
        
        .section-title {
          font-size: 16px;
          font-weight: bold;
          color: #1F2937;
          margin-bottom: 10px;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        
        .section-divider {
          border: none;
          border-top: 1px solid #D1D5DB;
          margin: 15px 0;
        }
        
        .diagnosis-box {
          background: #F3E8FF;
          padding: 20px;
          border-radius: 8px;
          border-left: 4px solid #7C3AED;
          margin: 10px 0;
        }
        
        .diagnosis-text {
          font-size: 24px;
          font-weight: bold;
          color: #581C87;
        }
        
        .info-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 15px;
          margin: 10px 0;
        }
        
        .info-item {
          padding: 12px;
          background: #F9FAFB;
          border-radius: 6px;
          border: 1px solid #E5E7EB;
        }
        
        .info-label {
          font-size: 12px;
          color: #6B7280;
          text-transform: uppercase;
          margin-bottom: 5px;
        }
        
        .info-value {
          font-size: 16px;
          font-weight: 600;
          color: #1F2937;
        }
        
        .risk-container {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 15px;
          margin: 10px 0;
        }
        
        .risk-item {
          padding: 15px;
          background: #F9FAFB;
          border-radius: 8px;
          border: 2px solid #E5E7EB;
        }
        
        .risk-label {
          font-size: 13px;
          color: #6B7280;
          margin-bottom: 8px;
          font-weight: 500;
        }
        
        .risk-value {
          font-size: 18px;
          font-weight: bold;
          text-transform: uppercase;
        }
        
        .risk-high { color: #DC2626; }
        .risk-moderate { color: #F59E0B; }
        .risk-low { color: #10B981; }
        .risk-unknown { color: #6B7280; }
        
        .recommendations-list {
          list-style: none;
          counter-reset: recommendation;
          margin: 10px 0;
        }
        
        .recommendations-list li {
          counter-increment: recommendation;
          padding: 12px;
          margin-bottom: 8px;
          background: #F0FDF4;
          border-left: 4px solid #10B981;
          border-radius: 4px;
        }
        
        .recommendations-list li:before {
          content: counter(recommendation) ". ";
          font-weight: bold;
          color: #10B981;
          margin-right: 8px;
        }
        
        .rules-list {
          list-style: none;
          margin: 10px 0;
        }
        
        .rules-list li {
          padding: 10px 15px;
          margin-bottom: 6px;
          background: #FEF3C7;
          border-left: 3px solid #F59E0B;
          border-radius: 4px;
          font-size: 14px;
        }
        
        .rules-list li:before {
          content: "• ";
          color: #F59E0B;
          font-weight: bold;
          margin-right: 8px;
        }
        
        .rule-summary {
          padding: 15px;
          background: #FEF3C7;
          border-radius: 8px;
          margin: 10px 0;
          text-align: center;
          font-weight: 600;
          color: #92400E;
        }
        
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 2px solid #E5E7EB;
          text-align: center;
          color: #6B7280;
          font-size: 12px;
        }
        
        .footer-brand {
          font-weight: bold;
          color: #7C3AED;
          margin-top: 10px;
        }
        
        @media print {
          body {
            padding: 20px;
          }
          
          .section {
            page-break-inside: avoid;
          }
          
          .meta-info, .info-grid, .risk-container {
            display: block;
          }
          
          .meta-info > div, .info-grid > div, .risk-container > div {
            margin-bottom: 10px;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">Sleep Health Screening Report</div>
        <div class="separator"></div>
      </div>
      
      <div class="meta-info">
        <div><strong>Date:</strong> ${timestamp || new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })}</div>
        <div><strong>Screening ID:</strong> ${results.screeningId || 'N/A'}</div>
      </div>
      
      <div class="section-divider"></div>
      
      <!-- DIAGNOSIS -->
      <div class="section">
        <div class="section-title">Diagnosis</div>
        <div class="section-divider"></div>
        <div class="diagnosis-box">
          <div class="diagnosis-text">${results.diagnosis || 'No Sleep Disorder Detected'}</div>
        </div>
      </div>
      
      <!-- TEST RESULT -->
      <div class="section">
        <div class="section-title">Test Result</div>
        <div class="section-divider"></div>
        <div class="info-grid">
          ${results.inputData?.sleepQualityScore !== undefined ? `
            <div class="info-item">
              <div class="info-label">Sleep Quality</div>
              <div class="info-value">${results.inputData.sleepQualityScore}/10</div>
            </div>
          ` : ''}
          ${results.inputData?.bmiCategory ? `
            <div class="info-item">
              <div class="info-label">BMI Category</div>
              <div class="info-value">${results.inputData.bmiCategory}</div>
            </div>
          ` : ''}
          ${results.inputData?.sleepDuration !== undefined ? `
            <div class="info-item">
              <div class="info-label">Sleep Duration</div>
              <div class="info-value">${results.inputData.sleepDuration} hours</div>
            </div>
          ` : ''}
          ${results.inputData?.stressLevel !== undefined ? `
            <div class="info-item">
              <div class="info-label">Stress Level</div>
              <div class="info-value">${results.inputData.stressLevel}/10</div>
            </div>
          ` : ''}
        </div>
      </div>
      
      <!-- RISK ASSESSMENT -->
      <div class="section">
        <div class="section-title">Risk Assessment</div>
        <div class="section-divider"></div>
        <div class="risk-container">
          <div class="risk-item">
            <div class="risk-label">Insomnia Risk</div>
            <div class="risk-value risk-${(results.insomniaRisk || 'unknown').toLowerCase()}">
              ${(results.insomniaRisk || 'UNKNOWN').toUpperCase()}
            </div>
          </div>
          <div class="risk-item">
            <div class="risk-label">Sleep Apnea Risk</div>
            <div class="risk-value risk-${(results.apneaRisk || 'unknown').toLowerCase()}">
              ${(results.apneaRisk || 'UNKNOWN').toUpperCase()}
            </div>
          </div>
        </div>
      </div>
      
      <!-- RECOMMENDATIONS -->
      ${results.recommendations && results.recommendations.length > 0 ? `
      <div class="section">
        <div class="section-title">Recommendations</div>
        <div class="section-divider"></div>
        <ul class="recommendations-list">
          ${results.recommendations.map(rec => `
            <li>${rec.replace('REC_', '').replace(/_/g, ' ')}</li>
          `).join('')}
        </ul>
      </div>
      ` : ''}
      
      <!-- RULE ENGINE ANALYSIS -->
      ${results.firedRules && results.firedRules.length > 0 ? `
      <div class="section">
        <div class="section-title">Rule Engine Analysis</div>
        <div class="section-divider"></div>
        <div class="rule-summary">
          Total Rules Fired: ${results.firedRules.length}
        </div>
        <div style="margin: 15px 0; padding: 12px; background: #FEF3C7; border-radius: 8px; font-size: 14px; color: #92400E;">
          <strong>Fired Rules:</strong> ${results.firedRules.join(', ')}
        </div>
        <ul class="rules-list">
          ${results.firedRules.map(rule => `
            <li><strong>${rule}:</strong> ${getRuleDescription(rule)}</li>
          `).join('')}
        </ul>
      </div>
      ` : ''}
      
      <div class="section-divider"></div>
      
      <div class="footer">
        <p><strong>Disclaimer:</strong> This report is generated by an automated screening system and should not replace professional medical advice.</p>
        <p>Please consult with a healthcare professional for proper diagnosis and treatment.</p>
        <div class="footer-brand">Generated by Kumeowturu</div>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();

  // Wait for content to load, then trigger print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };
};

/**
 * Share results (copy link to clipboard)
 */
export const shareResults = (screeningId) => {
  const url = `${window.location.origin}/results?id=${screeningId}`;

  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(url).then(() => {
      return true;
    }).catch(() => {
      return false;
    });
  } else {
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = url;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();

    try {
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      document.body.removeChild(textArea);
      return false;
    }
  }
};
